name: Java CI
on:
  push:
    branches:
      - developpement
      - '**/feature.*/'


  #release:
       #branches:
         # - test
         # - master
       #types: created


jobs:
  job1:
    name: job1 Starting with a Maven workflow template
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # The checkout step downloads a copy of your repository on the runner.
      - name: set up node
        uses: actions/setup-node@v1
      - name: Install bats
        run: npm install -g bats
      - name: execute a cmd
        run: bats -v
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn -B package --file pom.xml